In [1]:
import pandas as pd
df = pd.read_csv('Event.csv')
df

Opportunity         Time  Stage                Action
0          OP001  43456.60550      1        Emailed Client
1          OP001  43466.19231      1        Emailed Client
2          OP001  43471.51592      2   Meeting with Client
3          OP001  43479.39509      3   Presented to Client
4          OP001  43483.32009      3   Presented to Client
...          ...          ...    ...                   ...
1495       OP100  43515.50411      8  Prepared Commercials
1496       OP100  43525.75550      8  Prepared Commercials
1497       OP100  43529.26036      9   Negotiation Meeting
1498       OP100  43532.30689     11    Post Sales Support
1499       OP100  43534.78745     11    Post Sales Support

[1500 rows x 4 columns]

In [2]:
df.head()

Opportunity         Time  Stage               Action
0       OP001  43456.60550      1       Emailed Client
1       OP001  43466.19231      1       Emailed Client
2       OP001  43471.51592      2  Meeting with Client
3       OP001  43479.39509      3  Presented to Client
4       OP001  43483.32009      3  Presented to Client

In [3]:
df.describe()

Time        Stage
count   1500.000000  1500.000000
mean   43501.525641     6.018667
std       30.900761     3.154619
min    43454.605500     1.000000
25%    43475.654113     3.000000
50%    43498.247170     6.000000
75%    43524.348560     9.000000
max    43589.303420    11.000000

In [4]:
df['Event Key'] = df['Stage'].astype(str) + '-' + df['Action']

In [5]:
df

Opportunity         Time  Stage                Action  \
0          OP001  43456.60550      1        Emailed Client   
1          OP001  43466.19231      1        Emailed Client   
2          OP001  43471.51592      2   Meeting with Client   
3          OP001  43479.39509      3   Presented to Client   
4          OP001  43483.32009      3   Presented to Client   
...          ...          ...    ...                   ...   
1495       OP100  43515.50411      8  Prepared Commercials   
1496       OP100  43525.75550      8  Prepared Commercials   
1497       OP100  43529.26036      9   Negotiation Meeting   
1498       OP100  43532.30689     11    Post Sales Support   
1499       OP100  43534.78745     11    Post Sales Support   

                   Event Key  
0           1-Emailed Client  
1           1-Emailed Client  
2      2-Meeting with Client  
3      3-Presented to Client  
4      3-Presented to Client  
...                      ...  
1495  8-Prepared Commercials  
1496  8-Prepared Commercials  
1497   9-Negotiation Meeting  
1498   11-Post Sales Support  
1499   11-Post Sales Support  

[1500 rows x 5 columns]

In [6]:
df.head()

Opportunity         Time  Stage               Action              Event Key
0       OP001  43456.60550      1       Emailed Client       1-Emailed Client
1       OP001  43466.19231      1       Emailed Client       1-Emailed Client
2       OP001  43471.51592      2  Meeting with Client  2-Meeting with Client
3       OP001  43479.39509      3  Presented to Client  3-Presented to Client
4       OP001  43483.32009      3  Presented to Client  3-Presented to Client

In [7]:
events = list(df['Event Key'].unique())
events

['1-Emailed Client',
 '2-Meeting with Client',
 '3-Presented to Client',
 '4-Prepared Custom Demonstration',
 '5-Prepared POC',
 '6-Provided Pre-Sales Support',
 '8-Prepared Commercials',
 '9-Negotiation Meeting',
 '11-Post Sales Support',
 '7-Prepared RFP Responses',
 '10-Commercials Signed']

In [8]:
events = ['0-Dummy'] + events
events

['0-Dummy',
 '1-Emailed Client',
 '2-Meeting with Client',
 '3-Presented to Client',
 '4-Prepared Custom Demonstration',
 '5-Prepared POC',
 '6-Provided Pre-Sales Support',
 '8-Prepared Commercials',
 '9-Negotiation Meeting',
 '11-Post Sales Support',
 '7-Prepared RFP Responses',
 '10-Commercials Signed']

Create Series

In [9]:
series_length = 5
categories = len(events)
time_steps = series_length - 1


In [10]:
df.set_index('Opportunity', inplace= True)

In [11]:
df

Time  Stage                Action               Event Key
Opportunity                                                                  
OP001        43456.60550      1        Emailed Client        1-Emailed Client
OP001        43466.19231      1        Emailed Client        1-Emailed Client
OP001        43471.51592      2   Meeting with Client   2-Meeting with Client
OP001        43479.39509      3   Presented to Client   3-Presented to Client
OP001        43483.32009      3   Presented to Client   3-Presented to Client
...                  ...    ...                   ...                     ...
OP100        43515.50411      8  Prepared Commercials  8-Prepared Commercials
OP100        43525.75550      8  Prepared Commercials  8-Prepared Commercials
OP100        43529.26036      9   Negotiation Meeting   9-Negotiation Meeting
OP100        43532.30689     11    Post Sales Support   11-Post Sales Support
OP100        43534.78745     11    Post Sales Support   11-Post Sales Support

[1500 rows x 4 columns]

In [12]:
df.head()

Time  Stage               Action              Event Key
Opportunity                                                                
OP001        43456.60550      1       Emailed Client       1-Emailed Client
OP001        43466.19231      1       Emailed Client       1-Emailed Client
OP001        43471.51592      2  Meeting with Client  2-Meeting with Client
OP001        43479.39509      3  Presented to Client  3-Presented to Client
OP001        43483.32009      3  Presented to Client  3-Presented to Client

In [13]:
df.tail()

Time  Stage                Action               Event Key
Opportunity                                                                  
OP100        43515.50411      8  Prepared Commercials  8-Prepared Commercials
OP100        43525.75550      8  Prepared Commercials  8-Prepared Commercials
OP100        43529.26036      9   Negotiation Meeting   9-Negotiation Meeting
OP100        43532.30689     11    Post Sales Support   11-Post Sales Support
OP100        43534.78745     11    Post Sales Support   11-Post Sales Support

In [14]:
history = []
for op in df.index:
  for x in range(len(df['Stage'].loc[op].values) - series_length):
    history.append(df['Stage'].loc[op].values[x:x+series_length])

In [15]:
history

[array([1, 1, 2, 3, 3]),
 array([1, 2, 3, 3, 3]),
 array([2, 3, 3, 3, 4]),
 array([3, 3, 3, 4, 5]),
 array([3, 3, 4, 5, 5]),
 array([3, 4, 5, 5, 6]),
 array([4, 5, 5, 6, 6]),
 array([5, 5, 6, 6, 6]),
 array([5, 6, 6, 6, 8]),
 array([6, 6, 6, 8, 9]),
 array([6, 6, 8, 9, 9]),
 array([ 6,  8,  9,  9, 11]),
 array([1, 1, 2, 3, 3]),
 array([1, 2, 3, 3, 3]),
 array([2, 3, 3, 3, 4]),
 array([3, 3, 3, 4, 5]),
 array([3, 3, 4, 5, 5]),
 array([3, 4, 5, 5, 6]),
 array([4, 5, 5, 6, 6]),
 array([5, 5, 6, 6, 6]),
 array([5, 6, 6, 6, 8]),
 array([6, 6, 6, 8, 9]),
 array([6, 6, 8, 9, 9]),
 array([ 6,  8,  9,  9, 11]),
 array([1, 1, 2, 3, 3]),
 array([1, 2, 3, 3, 3]),
 array([2, 3, 3, 3, 4]),
 array([3, 3, 3, 4, 5]),
 array([3, 3, 4, 5, 5]),
 array([3, 4, 5, 5, 6]),
 array([4, 5, 5, 6, 6]),
 array([5, 5, 6, 6, 6]),
 array([5, 6, 6, 6, 8]),
 array([6, 6, 6, 8, 9]),
 array([6, 6, 8, 9, 9]),
 array([ 6,  8,  9,  9, 11]),
 array([1, 1, 2, 3, 3]),
 array([1, 2, 3, 3, 3]),
 array([2, 3, 3, 3, 4]),
 array([3,

In [21]:
history[1]

array([1, 2, 3, 3, 3])

In [19]:
df.head()

Time  Stage               Action              Event Key
Opportunity                                                                
OP001        43456.60550      1       Emailed Client       1-Emailed Client
OP001        43466.19231      1       Emailed Client       1-Emailed Client
OP001        43471.51592      2  Meeting with Client  2-Meeting with Client
OP001        43479.39509      3  Presented to Client  3-Presented to Client
OP001        43483.32009      3  Presented to Client  3-Presented to Client

In [20]:
df.describe()

Time        Stage
count   1500.000000  1500.000000
mean   43501.525641     6.018667
std       30.900761     3.154619
min    43454.605500     1.000000
25%    43475.654113     3.000000
50%    43498.247170     6.000000
75%    43524.348560     9.000000
max    43589.303420    11.000000

In [23]:
import numpy as np
np.array(history).shape

(16176, 5)

In [24]:
from tensorflow.keras.utils import to_categorical

In [25]:
X = np.array([row[:time_steps] for row in history])


In [26]:
X

array([[1, 1, 2, 3],
       [1, 2, 3, 3],
       [2, 3, 3, 3],
       ...,
       [6, 6, 7, 8],
       [6, 7, 8, 8],
       [7, 8, 8, 9]])

In [27]:
X = to_categorical(X)

In [28]:
X

array([[[0., 1., 0., ..., 0., 0., 0.],
        [0., 1., 0., ..., 0., 0., 0.],
        [0., 0., 1., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 1., 0., ..., 0., 0., 0.],
        [0., 0., 1., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 1., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       ...,

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 1., 0., 0.]]], dtype=float32)

In [30]:
X.shape

(16176, 4, 12)

In [31]:
y = np.array([row[time_steps] for row in history])


In [32]:
y = to_categorical(y).reshape(-1,categories)

In [34]:
y.shape

(16176, 12)

In [35]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

In [36]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense

In [40]:
model = Sequential()
model.add(LSTM(10,activation='relu', return_sequences=True, input_shape=(time_steps, categories)))
model.add(LSTM(10,activation='relu'))
model.add(Dense(categories, activation='softmax'))
model.compile('adam', loss = 'categorical_crossentropy')

In [41]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm (LSTM)                 (None, 4, 10)             920       
                                                                 
 lstm_1 (LSTM)               (None, 10)                840       
                                                                 
 dense (Dense)               (None, 12)                132       
                                                                 
Total params: 1,892
Trainable params: 1,892
Non-trainable params: 0
_________________________________________________________________


In [42]:
model.fit(X_train,y_train, epochs=10)

Epoch 1/10
405/405 [==============================] - 5s 5ms/step - loss: 1.6626
Epoch 2/10
405/405 [==============================] - 2s 6ms/step - loss: 1.0935
Epoch 3/10
405/405 [==============================] - 2s 6ms/step - loss: 1.0294
Epoch 4/10
405/405 [==============================] - 3s 8ms/step - loss: 0.9992
Epoch 5/10
405/405 [==============================] - 2s 5ms/step - loss: 0.9855
Epoch 6/10
405/405 [==============================] - 2s 6ms/step - loss: 0.9748
Epoch 7/10
405/405 [==============================] - 2s 6ms/step - loss: 0.9647
Epoch 8/10
405/405 [==============================] - 2s 5ms/step - loss: 0.9578
Epoch 9/10
405/405 [==============================] - 3s 7ms/step - loss: 0.9499
Epoch 10/10
405/405 [==============================] - 2s 5ms/step - loss: 0.9452


In [43]:
prediction = model.predict(X_test)


102/102 [==============================] - 1s 3ms/step


In [44]:
prediction

array([[2.28793922e-07, 3.46592442e-11, 4.09566131e-10, ...,
        7.54970387e-02, 6.50709402e-03, 4.41571365e-06],
       [6.17873468e-08, 1.30233415e-08, 2.74348668e-06, ...,
        7.58370990e-03, 1.38975435e-03, 8.05282028e-08],
       [1.40845587e-13, 1.36865979e-21, 2.90467499e-24, ...,
        6.07911170e-01, 3.30078363e-01, 6.02335073e-02],
       ...,
       [1.62644949e-06, 3.30304897e-06, 5.51234782e-01, ...,
        6.09797610e-07, 1.89157618e-05, 5.61446495e-06],
       [1.50360665e-06, 2.10075896e-07, 3.39695398e-04, ...,
        4.49830852e-03, 1.12133976e-02, 4.15480958e-04],
       [1.15407705e-12, 4.98341018e-21, 4.89236821e-24, ...,
        7.07622886e-01, 1.68207303e-01, 2.86649857e-02]], dtype=float32)

In [45]:
events[np.argmax(prediction[1])]

'5-Prepared POC'

In [46]:
np.argmax(y_test[1])

5

In [47]:
y_test[1]

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.], dtype=float32)

In [48]:
np.argmax(prediction[1])

5

In [54]:
from sklearn.metrics import accuracy_score

# y_true: true labels of test data
# y_pred: predicted labels of test data
accuracy = accuracy_score(y_train, prediction)

print('Accuracy:', accuracy)

ValueError: ignored